#!/bin/bash

BENCHMARKS="reverse tak rfib exp3_8"
CONFIGS="refcnt-opt gc-opt"

function usage {
  cat >&2 << EOF
Executes all of the benchmark programs.

The programs are: \"$BENCHMARKS\".
The configurations are: \"$CONFIGS\".

USAGE
    bench [-M|s]

        -M
            Do not remake the benchmarks (run only).

        -l
            Output a long report of the timing results.

        -q
            Work silently.
EOF
  exit 1;
}

SHORT_FLAG="-s"
NO_MAKE=0
QUIET=0

while getopts "Mlq" OPTION
do
  case $OPTION in
    l)
      SHORT_FLAG=""
      ;;
    M)
      NO_MAKE=1
      ;;
    q)
      QUIET=1
      ;;
  esac
done

shift $(($OPTIND - 1))

if [ "$#" != "0" ]; then
  usage
  exit 1
fi

ROOT=`(cd "\`dirname \"$0\"\`" > /dev/null ; cd ..; pwd)`
cd $ROOT

if [[ $QUIET == 1 ]]; then
  QUIET_OPTION="-q"
else
  QUIET_OPTION=""
fi


# Build.
if [[ $NO_MAKE == 0 ]]; then
  for CONFIG in $CONFIGS
  do
    ./scripts/make-benchmarks -c $CONFIG $QUIET_OPTION $BENCHMARKS
  done

  if [[ $QUIET == 0 ]]; then
    echo
    echo
  fi
fi


# Run.
for CONFIG in $CONFIGS
do
  echo "------ Config $CONFIG ------"
  ./scripts/install-benchmarks -c $CONFIG -q $BENCHMARKS
  ./scripts/run-benchmarks $SHORT_FLAG $BENCHMARKS 2>&1
done
